// Generated by gencpp from file milestone2/pathPlanning.msg
// DO NOT EDIT!


#ifndef MILESTONE2_MESSAGE_PATHPLANNING_H
#define MILESTONE2_MESSAGE_PATHPLANNING_H

#include <ros/service_traits.h>


#include <milestone2/pathPlanningRequest.h>
#include <milestone2/pathPlanningResponse.h>


namespace milestone2
{

struct pathPlanning
{

typedef pathPlanningRequest Request;
typedef pathPlanningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pathPlanning
} // namespace milestone2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::milestone2::pathPlanning > {
  static const char* value()
  {
    return "60da1f4dc44e1c3e5e24bf52a981d0f9";
  }

  static const char* value(const ::milestone2::pathPlanning&) { return value(); }
};

template<>
struct DataType< ::milestone2::pathPlanning > {
  static const char* value()
  {
    return "milestone2/pathPlanning";
  }

  static const char* value(const ::milestone2::pathPlanning&) { return value(); }
};


// service_traits::MD5Sum< ::milestone2::pathPlanningRequest> should match
// service_traits::MD5Sum< ::milestone2::pathPlanning >
template<>
struct MD5Sum< ::milestone2::pathPlanningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::milestone2::pathPlanning >::value();
  }
  static const char* value(const ::milestone2::pathPlanningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::milestone2::pathPlanningRequest> should match
// service_traits::DataType< ::milestone2::pathPlanning >
template<>
struct DataType< ::milestone2::pathPlanningRequest>
{
  static const char* value()
  {
    return DataType< ::milestone2::pathPlanning >::value();
  }
  static const char* value(const ::milestone2::pathPlanningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::milestone2::pathPlanningResponse> should match
// service_traits::MD5Sum< ::milestone2::pathPlanning >
template<>
struct MD5Sum< ::milestone2::pathPlanningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::milestone2::pathPlanning >::value();
  }
  static const char* value(const ::milestone2::pathPlanningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::milestone2::pathPlanningResponse> should match
// service_traits::DataType< ::milestone2::pathPlanning >
template<>
struct DataType< ::milestone2::pathPlanningResponse>
{
  static const char* value()
  {
    return DataType< ::milestone2::pathPlanning >::value();
  }
  static const char* value(const ::milestone2::pathPlanningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MILESTONE2_MESSAGE_PATHPLANNING_H
