// Generated by gencpp from file milestone2/pathPlanningResponse.msg
// DO NOT EDIT!


#ifndef MILESTONE2_MESSAGE_PATHPLANNINGRESPONSE_H
#define MILESTONE2_MESSAGE_PATHPLANNINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace milestone2
{
template <class ContainerAllocator>
struct pathPlanningResponse_
{
  typedef pathPlanningResponse_<ContainerAllocator> Type;

  pathPlanningResponse_()
    : plannedPath()  {
    }
  pathPlanningResponse_(const ContainerAllocator& _alloc)
    : plannedPath(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _plannedPath_type;
  _plannedPath_type plannedPath;





  typedef boost::shared_ptr< ::milestone2::pathPlanningResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::milestone2::pathPlanningResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pathPlanningResponse_

typedef ::milestone2::pathPlanningResponse_<std::allocator<void> > pathPlanningResponse;

typedef boost::shared_ptr< ::milestone2::pathPlanningResponse > pathPlanningResponsePtr;
typedef boost::shared_ptr< ::milestone2::pathPlanningResponse const> pathPlanningResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::milestone2::pathPlanningResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::milestone2::pathPlanningResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::milestone2::pathPlanningResponse_<ContainerAllocator1> & lhs, const ::milestone2::pathPlanningResponse_<ContainerAllocator2> & rhs)
{
  return lhs.plannedPath == rhs.plannedPath;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::milestone2::pathPlanningResponse_<ContainerAllocator1> & lhs, const ::milestone2::pathPlanningResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace milestone2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::milestone2::pathPlanningResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::milestone2::pathPlanningResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::milestone2::pathPlanningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::milestone2::pathPlanningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::milestone2::pathPlanningResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::milestone2::pathPlanningResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::milestone2::pathPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ed23ddc4e8131abb32610932f89b487";
  }

  static const char* value(const ::milestone2::pathPlanningResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ed23ddc4e8131abULL;
  static const uint64_t static_value2 = 0xb32610932f89b487ULL;
};

template<class ContainerAllocator>
struct DataType< ::milestone2::pathPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "milestone2/pathPlanningResponse";
  }

  static const char* value(const ::milestone2::pathPlanningResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::milestone2::pathPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/Path plannedPath\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::milestone2::pathPlanningResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::milestone2::pathPlanningResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plannedPath);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pathPlanningResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::milestone2::pathPlanningResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::milestone2::pathPlanningResponse_<ContainerAllocator>& v)
  {
    s << indent << "plannedPath: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.plannedPath);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MILESTONE2_MESSAGE_PATHPLANNINGRESPONSE_H
